name: infra

on:
  workflow_dispatch

jobs:
  terraform-docker:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v1
       - name: Check 
         env:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_NAME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_NAME }}
         run: |
           echo $kubeconfig > ${PWD}/terraform/kubeconfig
           docker run -v ${PWD}/terraform:/terraform -w /terraform  hashicorp/terraform:latest init
           docker run -v ${PWD}/terraform:/terraform -w /terraform  hashicorp/terraform:latest validate
           docker run -v ${PWD}/terraform:/terraform -w /terraform  hashicorp/terraform:latest plan
