name: infra

on:
  workflow_dispatch

jobs:
  terraform-docker:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - name: Check
         env:
             AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_NAME }}
             AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_NAME }}
         run:
           echo "AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID > .env1
           echo "AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY >> .env1
           docker run -v ${PWD}/terraform:/terraform -w /terraform --env-file .env1  $image init
           docker run -v ${PWD}/terraform:/terraform -w /terraform --env-file .env1  $image validate
           docker run -v ${PWD}/terraform:/terraform -w /terraform --env-file .env1  $image plan
