name: infra

on:
  workflow_dispatch

jobs:
  terraform-docker:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - name: Check 
       - uses: microsoft/variable-substitution@v1
         with:
             files: 'terraform/kubeconfig'
         env:
             kubeconfig: ${{ secrets.KUBECONFIG }}
       - uses: microsoft/variable-substitution@v1
         with:
             files: '.env'
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_NAME }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_NAME }}
         run: |
           echo "$bucket"
           echo $bucket
           echo $image
           echo "$AWS_ACCESS_KEY_ID"
           echo $kubeconfig > ${PWD}/terraform/kubeconfig
           echo AWS_ACCESS_KEY_ID="${{ secrets.S3_ACCESS_NAME }}" > .env
           echo AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" >> .env
           cat .env | wc
#           docker run -v ${PWD}/terraform:/terraform -w /terraform --env-file .env  $image init
#           docker run -v ${PWD}/terraform:/terraform -w /terraform --env-file .env  $image validate
#           docker run -v ${PWD}/terraform:/terraform -w /terraform --env-file .env  $image plan
