name: infra

on:
  workflow_dispatch

jobs:
  terraform-docker:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v1
       - name: Check 
         env:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_NAME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_NAME }}
          image: "hashicorp/terraform:1.0.2"
         run: |
           echo $kubeconfig > ${PWD}/terraform/kubeconfig
           docker run -v ${PWD}/terraform:/terraform -w /terraform -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY  $image init
           docker run -v ${PWD}/terraform:/terraform -w /terraform -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY  $image validate
           docker run -v ${PWD}/terraform:/terraform -w /terraform -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY  $image plan
