name: infra

on:
  workflow_dispatch

jobs:
  terraform-docker:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - name: Check
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_NAME }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_NAME }}
           image: "hashicorp/terraform"
         run: |
           echo ${{ secrets.KUBECONFIG }} | base64 --decode > terraform/kubeconfig
           echo "AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID > .env1
           echo "AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY >> .env1
           docker run -rm -v ${PWD}/terraform:/terraform -w /terraform -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY  $image init
           docker run -rm -v ${PWD}/terraform:/terraform -w /terraform -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY  $image validate
           docker run -rm -v ${PWD}/terraform:/terraform -w /terraform -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY  $image plan
